### PR TITLE
refactor: refactored auth

### PR DESCRIPTION
**Pull request by rexyness**
# Description

Refactored The authentication to have both the current user and is appleSignInAvailable in a single StateNotifierProvider to be used in AppNavigator widget 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The QA checklist below has been completed

### CODE REVIEW

**Comment by Afsal102** [comment]
@rexyness  hey is this still up? there are conflicts and the tests are missing!

**Comment by Afsal102** [comment]
@tadaspetra  seems this pr is stale

**Comment by tadaspetra** [comment]
> @tadaspetra seems this pr is stale

Let's leave it up for a little longer. He might have just gotten busy, and it doesn't really hurt to just have it up

**Comment by tadaspetra** [comment]
Closing due to inactivity, feel free to open again if you come back to this

**Pull request closed without merging**
